config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  # GET /flats/1
  def show
    @flat = Flat.find(params[:id])
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
    @flat = Flat.find(params[:id])
  end

  # POST /flats
  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat, notice: 'Flat was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /flats/1
  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'flat was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /flats/1
  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_url, notice: 'flat was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit%>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Show', @flat, class: "btn btn-primary" %> |
<%= link_to 'Back', flats_path, class: "btn btn-primary" %>

app/views/flats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ALL OUR FLATS</h1>

    <% @flats.each do |flat| %>

       <div class="card-trip">
  <img src="https://images.unsplash.com/photo-1614628079765-6c164f4bd970?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YXBwYXJ0ZW1lbnR8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60" />
  <div class="card-trip-infos">
    <div>
      <h2><%= flat.name %></h2>
      <p><%= flat.address %></p>
    </div>
    <h2 class="card-trip-pricing"><%= flat.number_of_guests %> persons</h2>
    <h2 class="card-trip-pricing"><%= flat.price_per_night %> $ per /night</h2>
  </div>
  </div>

  <br>
  <br>
        <div>
        <td><%= link_to 'Show', flat, class: "btn btn-flat" %></td>
        <td class="btn btn-primary btn-sm"><%= link_to 'Edit', edit_flat_path(flat), class: "btn btn-flat" %></td>
        <td class="btn btn-secondary btn-sm"><%= link_to 'Destroy', flat, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-ghost" %></td>
        <br>
        <br>
        </div>

        </div>

    <% end %>
<br>

<%= link_to 'New flat', new_flat_path %>

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Back', flats_path %>

app/views/flats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flat.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @flat.description %>
</p>

<p>
  <strong>Address:<strong>
  <%= @flat.address%>
</p>




<%= link_to 'Edit', edit_flat_path(@flat), class: "btn btn-primary" %> |
<%= link_to 'Back', flats_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>